version: 0.2

phases:
  install:
    commands:
      - echo "Instalando nvm..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - echo "Instalando Node 22..."
      - nvm install 22
      - nvm use 22
      - node -v
      - npm -v
      - echo "Instalando dependencias del proyecto..."
      - npm install

  pre_build:
    commands:
      - echo "Preparando para build..."

  build:
    commands:
      - echo "Construyendo proyecto Astro..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist